http://www.celestrak.org/NORAD/elements/amateur.txt
http://www.amsat.org/amsat/ftp/keps/current/nasa.all
http://www.celestrak.org/NORAD/elements/noaa.txt
http://www.celestrak.org/NORAD/elements/geo.txt
http://www.celestrak.org/NORAD/elements/weather.txt
http://www.celestrak.org/NORAD/elements/intelsat.txt
http://www.celestrak.org/NORAD/elements/cubesat.txt
http://www.celestrak.org/NORAD/elements/tle-new.txt
http://www.dk3wn.info/tle/amateur.txt
http://tle.pe0sat.nl/kepler/mykepler.txt
;
; Hints:
; The file contains the download addresses of Keplerian data files.
;
; To update Keplerian data proceed as follows:
; Open the SatPC32 menu "Satellites" and click on "Update Keps".
; In the list that opens select the proper file, then click on the 
; button "Download". The data file will then be downloaded and saved
; in the sub folder "Kepler" in the SatPC32 program folder (the SatPC32
; standard folder for Keplerian data files). 
;
; To use a data file  with SatPC32 open the menu "Satellites". In the
; left list click on the filename, then click on "OK". That will
; store the path and filename for future program starts.  
; 
; When you download an update of the file that has been chosen for 
; SatPC32 in the left list of the menu Satellites SatPC32 will
; automatcally use the new data from the next program start.
; 
; If you want to download other Keplerian data files add the addresses
; to the data section of this file. To find the address open the file
; with your browser and copy the address from the browser's 
; address line.
;
; Add only addresses of Http servers (addresses that start with 'Http'.
; Don't add addresses of FTP servers (addresses that start with 'FTP'. 
